### ISSUE TITLE
DiscoTOC broken when using this component

### ISSUE THREAD

**Issue by sevospl** [programmersforum-reborn/discourse-wide-posts#1]
DiscoTOC is broken when the width is changed.

**Comment by AlexP11223** [comment]
What do you mean?

I have DiscoTOC and it works fine for me, except that the first post does not become wider.

**Comment by sevospl** [comment]
My pardon. It turned out to be my custom theme causing this issue. Should have checked the default Discourse one before creating an issue.

**Comment by sevospl** [comment]
Which post width in % are you using right now?

**Comment by sevospl** [comment]
Which post width in % are you using right now?

**Comment by AlexP11223** [comment]
Default 75%.

**Comment by sevospl** [comment]
I just checked your forum. The table of contents is far from the post. By default, it's right next to the content post.

Your forum: https://i.imgur.com/xfPbaaA.png
Discourse by default: https://i.imgur.com/QfUZsdI.png

See the difference? That seems to me to be broken.

**Comment by AlexP11223** [comment]
Ah, yeah. It's unclear though what should be the correct behavior: make the first post wider too (and TOC narrower?) or keep the default sizes.

Also it seems more complex because in another topic it works differently: https://www.programmersforum.rocks/t/testovaya-tema/12

**Comment by sevospl** [comment]
On my forum it unfortunately looks even worse: https://i.imgur.com/8Cel8f2.png (even with 75%).

Looks more like TOC needs individual fix to complement wide posts nicely.

**Comment by AlexP11223** [comment]
For now I simply disabled it on TOC posts.

**Comment by sevospl** [comment]
Nice workaround - it's perfect now. Thanks!
